{{ range $index, $repository := .Values.repositories.hosted }}
apiVersion: maven.operator.io/v1alpha1
kind: MavenRepository
metadata:
  name: {{ $repository.name }}
spec:
  type: Hosted
  storage:
    size: {{ $repository.storage.size }}
  ingress:
    enabled: true
    host: hosted.{{ $.Values.gateway.domain }}
    certManager:
      issuerName: letsencrypt-production
      isClusterIssuer: true
      renewBefore: "1440h"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com"
  auth:
    download:
      policy: Anonymous          
    upload:
      policy: Authenticated
      users:
        - secretRef: credentials-orion
          role: Admin
      ciTrust:
        - platform: GitHubActions
          claims:
            repository_owner: communi-suggestu
{{ end }}