apiVersion: maven.operator.io/v1alpha1
kind: MavenRepository
metadata:
  name: public
spec:
  type: Virtual
  virtual:
    members:
      {{- range .Values.repositories.hosted }}
      - {{ .name | quote }}
      {{- end }}
  gateway:
    enabled: true
    gatewayRef:
      name: traefik-gateway
      namespace: traefik
    certManager:
      issuerName: letsencrypt-production
      isClusterIssuer: true
    hostname: {{ $.Values.gateway.domain }}
    routeAnnotations:
      external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com"
    extensionRefs:
      - group: traefik.io
        kind: Middleware
        name: waf-crs
  auth:
    download:
      policy: Anonymous
    upload:
      policy: Authenticated
      users: []
    