---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: credentials-orion
  namespace: communi-suggestu-maven
spec:
  encryptedData:
    password: AgA2iJgju5PqUc1SqyMIRNSu+3kbQcMmxIaxUOjWRRMtwuZOUo1Zh7cNsnAXku2i7G8ND+JUbN8Z8gz5IKyF3c4ArLPQnKvFTHGzqirGAR2AIWIzX6mTrjsNLL8xs36QUih46DiS4/v+e7qy1eKceR0rDPpb54MiVzaQamZ//dIYibLu+uvWP3TTfdcgaJZd6BIwItu/0mUJYSq/k1o4apbvGRts8Fi91oZ8q4yRWfqvJ4RZDa0fSKhmAjZHL4rbkl+KJLWoCln2ekY5by7Xw2EDbaD7y/wXELVHc1vTJSP48oMnALfXN4clzHWKQ69vwcjSVv3Iwk/HO/m6vO4Yf1m3/LbbvYrRqQiDYnEuPqiWxw5fsLqMMRDh9LHJWT1qA8QWBxrdKp0PsikEanSYZ+gn2bk0RYP5jUkJxfbdRRQDMa1ax6MOUxKSnyD7jdw41+rMO7HJqWFMErT3iF2mtmY4u6tVcB0vxnuB5Nu8yHy47ab241mx0UbiJOOQ9yRM2/Hqj6YQrLMgzi79WvyE51K3uUXQrMCIL7JDVNr+3hnSVjcbnIcYys7gB3qoUG4WI2yP8ZsYrqAsHc4ek1bKuDuhe+7kuptq0ONS73vCyeB9AjK5Y6PczwC3QGdu1K9sxSe4Lwv0GCHerczAiY5F7BMDo2otSMvhMVP1brCuQwz6nNN/3/pDmJIuQFpzsqay0KKNuGrg/j3JT84=
    username: AgA0eF7JX5k5R8DYceQwQ7yC7iNfpLCJNexbt+WLaW+YOGk9mD4qr2NpZY+/LsgVfE3c3BBSmz2uWPF+4y2DvLNWyZ2KDSaa8og7dhL17Pr/fLP2lXB57vFllelMuyFCIRSbHS4PepkciSiLoK39N2PmRz1XB9fVRPeA8faOAt2ugS8wXlTEVSmhSHlORb8DWEmyjRiwqXOgZmGVnSMTEAv7OoEB9+DZCWvupvNMqwIW3Gs0ycC5uga4v43ujXDjl7WdFjJd/jtBYQcI59p64q/y3G1brzD7sRug7RyOL2fi42BUbhj1laC+5+NncWsYo5FHprd3RwCiWC53OI9OBBU0cKkh179fS2cooq8xgcmzQTazpqrIfQpqOLcWOe73aGVjSq+STcL6yN8xHPN42iKYxLix7oOrC7ccGAUHZS9oilXmYOZDE1msNC1bXXIQEQ5S3GjigLyYrv2DgORllDA0TlubmxPgUZBCIgPBc1v2duaL9l8QcGORXFE+WwGEnKFpDK6F9PvhB/l0T8CABCgEKjw9mN6oSoEkIoiR3nZzsrz2oJqAQ4bzQe79P5nKZZDjBVQ2yye4HAYDtoSmlQv4bg0ht6y9w2ynA7frkzMtQsqGODoonxYlRMMHijOqqx8GK6HfdlddIEdlllmAqdOYImVbgtpWSAhR3JaM/CFu2rsjI3INZFKpmPUjiyVq35CdJX5E4g==
  template:
    metadata:
      name: credentials-orion
      namespace: communi-suggestu-maven
      labels:
        app.kubernetes.io/part-of: maven
